src/frameworks/trigger-bypass-strategy/main/objects/BypassTriggers__c/BypassTriggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Hierarchical Custom Setting to control the bypassing of Triggers</description>
    <label>Bypass Triggers</label>
</CustomObject>

src/frameworks/trigger-bypass-strategy/main/objects/BypassTriggers__c/fields/Bypass__c.field-meta.xml
<CustomField>
    <fullName>Bypass__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to bypass Triggers</description>
    <label>Bypass All</label>
    <type>Checkbox</type>
</CustomField>

src/frameworks/trigger-bypass-strategy/test/classes/TriggerBypassStrategyTest.cls
@SuppressWarnings('sf:CommentRequired, sf:MethodNamingConventions')
@isTest
private class TriggerBypassStrategyTest {

    @isTest
    private static void should_not_be_disabled_if_no_settings_for_the_user() {
        final User runningUser = createUser('FirstName', 'LastName');
        Boolean isDisabled;
        System.runAs(runningUser) {
            isDisabled = new TriggerBypassStrategy().isDisabled();
        }

        System.assert(!isDisabled, 'Is Disabled should be false');
    }

    @SuppressWarnings('sf:AvoidDMLInUnitTests')
    @isTest
    private static void should_not_be_disabled_if_setting_is_set_to_false() {
        final User runningUser = createUser('FirstName2', 'LastName2');
        final BypassTriggers__c setting = new BypassTriggers__c(
            SetupOwnerId = runningUser.Id,
            Bypass__c = false
        );

        insert setting;
        Boolean isDisabled;
        System.runAs(runningUser) {
            isDisabled = new TriggerBypassStrategy().isDisabled();
        }

        System.assert(!isDisabled, 'Is Disabled should be false');
    }

    @isTest
    private static void should_be_disabled_if_setting_is_set_to_true() {
        final User runningUser = createUser('FirstName2', 'LastName2');
        final BypassTriggers__c setting = new BypassTriggers__c(
            SetupOwnerId = runningUser.Id,
            Bypass__c = true
        );
        insert setting;
        Boolean isDisabled;
        System.runAs(runningUser) {
            isDisabled = new TriggerBypassStrategy().isDisabled();
        }

        System.assert(isDisabled, 'Is Disabled should be true');
    }

    private static User createUser(String fName, String lName) {
        @SuppressWarnings('sf:shortVariable')
        final User u = new User(
                            LastName = lName,
                            FirstName = fName,
                            Email = 'testing@test.com',
                            Alias = 'TestAl',
                            Username = 'testing@test.com' + System.currentTimeMillis(),
                            TimeZoneSidKey = 'Australia/Sydney',
                            LanguageLocaleKey = 'en_US',
                            LocaleSidKey = 'en_AU',
                            EmailEncodingKey = 'ISO-8859-1',
                            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id
        );
        insert u;
        return u;
    }

}