src/frameworks/trigger-framework/main/objects/TriggerHandler__mdt/TriggerHandler__mdt.object-meta.xml
<CustomObject>
    <description>Trigger Handler registration</description>
    <label>Trigger Handler</label>
    <pluralLabel>Trigger Handlers</pluralLabel>
</CustomObject>

src/frameworks/trigger-framework/main/objects/TriggerHandler__mdt/fields/HandlerClass__c.field-meta.xml
<CustomField>
    <fullName>HandlerClass__c</fullName>
    <description>Trigger Handler Class Name</description>
    <label>Handler Class</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/frameworks/trigger-framework/main/objects/TriggerHandler__mdt/fields/HandlerDescription__c.field-meta.xml
<CustomField>
    <fullName>HandlerDescription__c</fullName>
    <description>Trigger Handler Description</description>
    <label>Handler Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/frameworks/trigger-framework/main/classes/CustomMetadataHandlerConfigProvider.cls
/**
 * @description Configuration Provider for Trigger Handlers based on custom
 * metadata
 */
public with sharing class CustomMetadataHandlerConfigProvider implements HandlerConfigProvider {
    /**
     * @description Provides the trigger configuration for the handlers that
     * need to be instantiated for a specific SObject
     * @param sObjectType filter on the SObject
     * @return trigger configurations for the SObject
     */
    public List<TriggerHandlerConfig> loadConfigurationBySObjectType(String sObjectType) {
        /** @description Trigger handlers configurations */
        final List<TriggerHandlerConfig> handlers = new List<TriggerHandlerConfig>();

        for (TriggerHandler__mdt config : this.getMetadataConfig(sObjectType)) {
            handlers.add(buildConfiguration(config));
        }

        return handlers;
    }

    /**
     * @description Fetches the required information to eventually dynamically
     * instantiate the Trigger Handler
     * @param sObjectType filter on the SObject
     * @return custom metadata entries for the SObject type
     */
    private List<TriggerHandler__mdt> getMetadataConfig(String sObjectType) {
        @SuppressWarnings('PMD.ApexCRUDViolation, sf:FieldLevelSecurity')
        final List<TriggerHandler__mdt> config =
            [SELECT MasterLabel,
                    HandlerClass__c,
                    HandlerDescription__c
                FROM TriggerHandler__mdt
                WHERE MasterLabel =: sObjectType];

        return config;
    }

    /** @description Builds a trigger handler configuration from a custom
     *  metadata record
     * @param config custom metadata record holding the configuration
     * @return a trigger handler configuration used to instantiate the trigger
     *  handler dynamically
     */
    private TriggerHandlerConfig buildConfiguration(TriggerHandler__mdt config) {
        return new TriggerHandlerConfig.Builder()
                    .triggerHandler(config.HandlerClass__c)
                    .description(config.HandlerDescription__c)
                    .build();
    }
}